class Config {
  final String title,
      logo,
      contact,
      whatsAppNumber,
      email,
      copyright,
      about,
      terms,
      termsTitle,
      razorPayKey,
      razorPaySecretKey,
      smsUserName,
      smsPassword,
      smsSenderId,
      smsFL,
      smsGwID;

  Config(
      {this.title,
      this.logo,
      this.contact,
      this.whatsAppNumber,
      this.email,
      this.copyright,
      this.about,
      this.terms,
      this.termsTitle,
      this.razorPayKey,
      this.razorPaySecretKey,
      this.smsUserName,
      this.smsPassword,
      this.smsSenderId,
      this.smsFL,
      this.smsGwID});

  Config.fromJson(Map<String, dynamic> json)
      : title = json['title'],
        logo = json['logo'],
        contact = json['contact'],
        whatsAppNumber = json['whatsapp_number'],
        email = json['email'],
        copyright = json['copyright'],
        about = json['about'],
        terms = json['terms'],
        termsTitle = json['terms_title'],
        razorPayKey = json['razorpay_key'],
        razorPaySecretKey = json['razorpay_secret_key'],
        smsUserName = json['sms_username'],
        smsPassword = json['sms_password'],
        smsSenderId = json['sms_sender_id'],
        smsFL = json['sms_fl'],
        smsGwID = json['sms_gwid'];
}
